
insert into parts (partName, partDescription, partSupplier, partNumber)
values
("Extension Rail", "Extension Rail", "DE", "TBD"),
("Cap Screw", "Fiberglass Hex Head Cap Scew", "McMaster", "91345A705"),
("Socket Cap Screw", "SS Flat Head Socket Cap Screw", "McMaster","92210A635"),
("Roll Plate", "Roll Plate, Back", "DE", "TBD"),
("Head Mount", "Circular Head Mount", "DE", "TBD"),
("Roll Plate", "SPWG Roll Plate", "DE", "TBD"),
("Mast Base", "Circular Mast Base", "DE", "TBD"),
("Mast Baseplate", "Mast Baseplate", "DE", "TBD"),
("Head Mount Brace", "Circular Head Mount Brace Base", "DE", "TBD"),
("Frame Top", "Frame Top", "DE", "TBD"),
("Frame Side", "Frame Side Short", "DE", "TBD"),
("Frame Side", "Frame Side Long", "DE", "TBD"),
("Stage Plate", "Stage Plate", "DE", "TBD"),
("Stage Bracket", "Stage Bracket", "DE","TBD"),
("Rotary Stage", "Rotary Stage", "DE", "TBD"),
("512-2400","512-2400", "Mcmaster", "512-2400"),
("HC Slip Ring ADP","HC Slip Ring ADP", "TBD", "TBD"),
("HC Slip Ring Tube","HC Slip Ring Tube", "TBD", "TBD"),
("HC SR Keeper","HC SR Keeper","TBD","TBD"),
("Rotary Stage", "Rotary Stage", "TBD", "TBD"),
("RingStyle Turntable", "Aluminum Ring Style Turntable", "TBD", "TBD"),
("Panel","Panel","TBD","TBD"),
("DB9 Connector","DB9 Connector","TBD","TBD"),
("DC Jack","DC Jack", "TBD", "TBD"),
("5mmGreenLED", "5mm Green LED", "TBD", "TBD"),
("SMA", "SMA", "TBD", "TBD"),
("Red Fan", "Sunnon Red Fan","Sunnon","TBD"),
("HSR20A", "HRS20A Slip Ring", "TBD", "HRS20A"),
("Arcylic Floor", "Plate Acrylic Floor","TBD","TBD"),
("Bearing Block", "Bearing Block BF10", "TBD", "BK10"),
("Ball Screw Block", "Ball Scre Block", "TBD", "TBD"),
("Motor Mount","NEMA17 Motor Mount","TBD","TBD"),
("Ball Bearing","1204 Ball Bearing","TBD","6661K820"),
("Motor","NEMA17 Motor","TBD","TBD"),
("Ball Nut","Ball Nut","TBD","TBD");


